/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_watanow_lbslogicpkg_LbsLogicMain */

#ifndef _Included_com_watanow_lbslogicpkg_LbsLogicMain
#define _Included_com_watanow_lbslogicpkg_LbsLogicMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_watanow_lbslogicpkg_LbsLogicMain
 * Method:    ndkLbsLogic
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_watanow_lbslogicpkg_LbsLogicMain_ndkLbsLogic
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_watanow_lbslogicpkg_LbsLogicMain
 * Method:    ndkLbsIntArrayLogic
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_watanow_lbslogicpkg_LbsLogicMain_ndkLbsIntArrayLogic
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_watanow_lbslogicpkg_LbsLogicMain
 * Method:    ndkLbsStringLogic
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_watanow_lbslogicpkg_LbsLogicMain_ndkLbsStringLogic
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_watanow_lbslogicpkg_LbsLogicMain
 * Method:    ndkLogic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_watanow_lbslogicpkg_LbsLogicMain_ndkLogic
  (JNIEnv *, jobject);

/*
 * Class:     com_watanow_lbslogicpkg_LbsLogicMain
 * Method:    ndkLogicInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_watanow_lbslogicpkg_LbsLogicMain_ndkLogicInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_watanow_lbslogicpkg_LbsLogicMain
 * Method:    ndkLogicChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_watanow_lbslogicpkg_LbsLogicMain_ndkLogicChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_watanow_lbslogicpkg_LbsLogicMain
 * Method:    ndkLogicCharArray
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_watanow_lbslogicpkg_LbsLogicMain_ndkLogicCharArray
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     com_watanow_lbslogicpkg_LbsLogicMain
 * Method:    startThread
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_watanow_lbslogicpkg_LbsLogicMain_startThread
  (JNIEnv *, jobject);

/*
 * Class:     com_watanow_lbslogicpkg_LbsLogicMain
 * Method:    endThread
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_watanow_lbslogicpkg_LbsLogicMain_endThread
  (JNIEnv *, jobject);

/*
 * Class:     com_watanow_lbslogicpkg_LbsLogicMain
 * Method:    getNumString
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_watanow_lbslogicpkg_LbsLogicMain_getNumString
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
