/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_watanow_lbslogicpkg_LbsLogicMain */

#ifndef _Included_com_watanow_lbslogicpkg_LbsLogicMain
#define _Included_com_watanow_lbslogicpkg_LbsLogicMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_watanow_lbslogicpkg_LbsLogicMain
 * Method:    ndkLbsLogic
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_watanow_lbslogicpkg_LbsLogicMain_ndkLbsLogic
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
